CREATE DATABASE "iBei"

CREATE TABLE "User" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"Username" VARCHAR(30) NOT NULL,
	"Password" VARCHAR(30) NOT NULL,
	"Email" VARCHAR(50) NOT NULL,
	"Active" BIT
);

CREATE TABLE "Auction" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"SellerId" UNIQUEIDENTIFIER NOT NULL,
	"Active" BIT,
	"EndTime" DATETIME NOT NULL,
	CONSTRAINT "FK_Auction_User_SellerId" FOREIGN KEY ("SellerId") REFERENCES "User"(Id)
);

CREATE TABLE "Bid" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"UserId" UNIQUEIDENTIFIER NOT NULL,
	"AuctionId" UNIQUEIDENTIFIER NOT NULL,
	"BidPrice" DECIMAL(18,2) NOT NULL,
	CONSTRAINT "FK_Bid_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User"("Id"),
	CONSTRAINT "FK_Bid_Auction_AuctionId" FOREIGN KEY ("AuctionId") REFERENCES "Auction"("Id")
);

CREATE TABLE "Item" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"CategoryId" UNIQUEIDENTIFIER NOT NULL,
	"Name" VARCHAR(50) NOT NULL,
	"Description" TEXT NOT NULL,
	CONSTRAINT "FK_Item_Auction_Id" FOREIGN KEY ("Id") REFERENCES "Auction"("Id")
);