CREATE DATABASE "iBei"

CREATE TABLE "User" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"Username" VARCHAR(30) NOT NULL,
	"Password" VARCHAR(30) NOT NULL,
	"Email" VARCHAR(50) NOT NULL,
	"Active" BIT
);