CREATE DATABASE "RecordCompany";

USE "RecordCompany";

CREATE TABLE "Band" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"Name" VARCHAR(50) NOT NULL,
);

CREATE TABLE "Albums" (
	"Id" UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	"Name" VARCHAR(50) NOT NULL,
	"ReleaseYear" INT,
	"BandId" UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT "FK_Albums_Band_BandId" FOREIGN KEY (BandId) REFERENCES Band(Id)
);